# Site settings
title: Your awesome title

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mib-barcelona.isdi.es" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
